# Generated by Django 2.0.2 on 2018-03-31 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('name', models.CharField(db_index=True, max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Article Statuses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(default='Not Provided', max_length=100)),
                ('company', models.CharField(default='Not Provided', max_length=200)),
                ('phone', models.CharField(default='Not Provided', max_length=20)),
                ('articles', models.ManyToManyField(blank=True, to='api.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleStatus'),
        ),
    ]
