# Generated by Django 2.0.2 on 2018-05-26 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=3000)),
                ('content', models.FileField(upload_to='pdf/')),
                ('udc', models.CharField(max_length=3000)),
                ('key_words', models.CharField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('collaborators', models.TextField()),
                ('number', models.IntegerField(default=0)),
                ('can_edit', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Article Stages',
            },
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Article Statuses',
            },
        ),
        migrations.CreateModel(
            name='ArticleTheme',
            fields=[
                ('theme', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Журнал <django.db.models.fields.DateTimeField>', max_length=200)),
                ('articles', models.ManyToManyField(to='api.Article')),
                ('theme', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleTheme')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(default='Not Provided', max_length=100)),
                ('position', models.CharField(default='Not Provided', max_length=200)),
                ('grade', models.CharField(blank=True, default='Not Provided', max_length=200)),
                ('company', models.CharField(default='Not Provided', max_length=200)),
                ('phone', models.CharField(default='Not Provided', max_length=20)),
                ('articles', models.ManyToManyField(blank=True, to='api.Article')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlestage',
            name='statuses_id',
            field=models.ManyToManyField(to='api.ArticleStatus'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='api.Language'),
        ),
        migrations.AddField(
            model_name='article',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleStage'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleStatus'),
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleTheme'),
        ),
    ]
