# Generated by Django 2.0.2 on 2018-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(default='Журнал 2018-06-03 16:30:04.657604', max_length=200),
        ),
    ]
