# Generated by Django 2.0.2 on 2018-05-01 07:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(default='it', on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleTheme'),
            preserve_default=False,
        ),
    ]
