# Generated by Django 2.0.2 on 2018-05-15 19:25

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('statuses_id', models.ManyToManyField(to='api.ArticleStatus')),
            ],
            options={
                'verbose_name_plural': 'Article Stages',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(default='Not Provided', max_length=100)),
                ('position', models.CharField(default='Not Provided', max_length=200)),
                ('company', models.CharField(default='Not Provided', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Журнал <django.db.models.fields.DateTimeField>', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='key_words',
            field=models.CharField(default='default keyword', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='udc',
            field=models.CharField(default='321312udc', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, default='Not Provided', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AddField(
            model_name='journal',
            name='articles',
            field=models.ManyToManyField(to='api.Article'),
        ),
        migrations.AddField(
            model_name='journal',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleTheme'),
        ),
        migrations.AddField(
            model_name='article',
            name='collaborators',
            field=models.ManyToManyField(to='api.Collaborator'),
        ),
        migrations.AddField(
            model_name='article',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.fields.NOT_PROVIDED, to='api.ArticleStage'),
        ),
    ]
