export const userActionTypes = {
    DEFINE_USER_REQUEST: 'DEFINE_USER_REQUEST',
    DEFINE_USER_SUCCESS: 'DEFINE_USER_SUCCESS',
    DEFINE_USER_FAILURE: 'DEFINE_USER_FAILURE',
    
    LOGOUT_USER: "LOGOUT_USER",
    
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_REQUEST: 'GET_USERS_REQUEST'
}

export const articleActionTypes = {
    ARTICLE_CREATION_REQUEST: ''
}
